### ISSUE TITLE
path is empty on results

### ISSUE THREAD

**Issue by diablade** [lafranceinsoumise/api-django#15]
le "path"  etait super utile pour rediriger sur le site officiel des evenements respectifs
en rajoutant a la mano lafranceinsoumise.fr/+path
il est desormais vide :/  
"path" : "",

**Comment by guilro** [comment]
Le "path" désignait l'URL de l'événement sur NationBuilder. Il n'est donc pas rempli pour les nouveau événements.

On va le faire évoluer pour afficher la nouvelle URL. Le nom de domaine sera par contre `agir.lafranceinsoumise.fr`.

Dans quel contexte utilises-tu l'API ?

**Comment by diablade** [comment]
pour faire un agenda auto remplis de tout les evenements autour de moi 
donc nationnalement possible (internationnal aussi) 
j suis en train de le dev sous angularJs avec ui.calendar
je peux te passer une demo  si tu veux

**Comment by guilro** [comment]
Avec plaisir ! Ça rejoint pas mal ce qu'on cherche à développer, on te piquera probablement des idées :)

**Comment by guilro** [comment]
Tu as la nouvelle path dans l'API !

**Comment by diablade** [comment]
y aurai pas moyen de vous rejoindre du coup ? vous etes sur le discord ?
j vais faire un github de mon code 
en attendant voila à quoi ca devrai ressemblé : http://88.182.11.63/agendaFi/

**Comment by guilro** [comment]
Non, on est pas sur le discord. Bien reçu ton lien :)

Tu peux me contacter sur twitter @guilrobis ?
