### ISSUE TITLE
Qui a lancé le programme? La seed est-elle publique?

### ISSUE THREAD

**Issue by rcaze** [lafranceinsoumise/api-django#16]
En effet il suffit de le lancer plusieurs fois pour obtenir le résultat que la personne qui lance le programme décide.

La seed va entièrement determiner le tirage en entier. Comment a-t-elle était choisie? Un projet pour la rendre publique? Ou rendre son tirage pour une prochaine fois publique?

**Comment by guilro** [comment]
Nous n'avons pas choisi de seed, nous utilisons l'état interne du générateur de PostgreSQL.

L'intérêt de se préoccuper de la seed est limité par le fait que la base de donnée évolue en permanence. Le tirage ne pourra de toute façon donc pas être déterministe.

**Comment by aktiur** [comment]
En l'occurrence, la seed est initialisée automatiquement par le serveur PostgreSQL au moment où le script s'y connecte, à partir du PID (numéro de process) du process serveur et du timestamp correspondant au début de la connexion : 
https://doxygen.postgresql.org/postmaster_8c_source.html#l04307

**Comment by rcaze** [comment]
Ca il faut vous faire confiance. J'ai confiance et bravo pour ce boulot :) Je me doute que vous n'avez pas choisi la seed mais une personne malintentionée pourrait le faire. 

La base de donnée évolue de façon permanente? Elle n'est pas fixe lors du tirage au sort.

Est-ce que vous seriez OK si j'essaye de rendre le code plus compréhensible par le plus grand nombre genre en commenttant en français? (après il me suffit de forker mais je préfère savoir si vous étiez interesser + conseils pour commencer) 

Bref encore bravo d'avoir lancer cette idée. D'ailleurs qui d'autre porte cette idée à part vous deux?

**Comment by aktiur** [comment]
Effectivement, une dose de confiance est nécessaire : mais ce serait aussi le cas avec un seed public, puisqu'il faudrait avoir un snapshop de la base de données au moment du vote pour pouvoir vérifier le résultat avec le seed, et ce n'est évidemment pas possible de diffuser les données personnelles...

Ce que voulait dire Guilro sur l'évolution de la base de données recouvre en fait deux choses :

* Nous ne sauvegardons pas la date d'inscription pour les tirages au sort : quand on tire au sort, on inclut dans le tirage l'ensemble des gens inscrits au moment du tirage. Donc pas possible en l'état de retrouver la liste des inscrits à la date du tirage (on pourrait utiliser les backups pour ça, mais ce serait pénible)
* Quand bien même on le ferait, cela ne rendrait pas le tirage déterministe : vu la requête, j'imagine que PostgreSQL fait un *sequential scan*, donc calcule probablement les valeurs `random` dans l'ordre physique des lignes de la table. Si un utilisateur modifie par exemple son prénom par la suite, cela crée une nouvelle ligne physique qui est ajoutée en bas de la table (les lignes sont immutables dans PostgreSQL, un update insère toujours une nouvelle ligne et indique l'ancienne comme obsolète, elle sera ensuite *garbage collected*). Du coup ça modifie l'ordre des lignes, et donc le résultat du tirage, avec pourtant le même *seed* et le même collège d'inscrits.

Tu peux nous proposer une pull request pour les commentaires

**Comment by rcaze** [comment]
La confiance ne devrait pas être nécessaire ou le moins possible. Et une seed rendue par la suite publique n'ajouterai pas tant que ça de confiance. Pour le bien il faudrait tirer au sort une seed (avec présence de témoins) utilisée par le programme et une liste d'identifiants anonymes (qu'on donne par exemple lors d'une inscription) pour améliorer la fiabilité du système. Un autre problème serait d’empêcher une personne de s'inscrire deux fois (et ainsi multiplier ses chances). Bref c'est le façon de tricher qui me viennent à l'esprit au bout de 5 min mais je suis sur qu'il y en a encore un tas d'autres. 

Je ne suis pas programmeur mais chercheur en neurosciences computationelles (je bosse donc avec du code et des ordis tout le temps). Et pourtant beaucoup de choses me paraissent incompréhensibles et/ou accessoires (rien que dans l'arborescence des fichiers), et je suis complètement novice avec beaucoup de termes techniques tels que "sequential scan" ou la phase de "garbage collected". Je sais que cela est pratique de travailler avec le SQL mais je connais plein de gens qui ne savent ce que c'est que le SQL.

Je pense que plus la dose de confiance nécessaire sera légère (script compréhensible et concis au maximum) plus cette méthode sera acceptée largement.

**Comment by rcaze** [comment]
La solution à ce problème est venu des marchés financiers :). http://www.stochocratie.org/2018/03/07/using-the-financial-market/
