### ISSUE TITLE
Erreur sur le formulaire de création d'évenement

### ISSUE THREAD

**Issue by sghribi** [lafranceinsoumise/api-django#20]
Sur le formulaire de création d'événements, cette ligne pose problème : https://github.com/lafranceinsoumise/api-django/blob/master/src/javascript_components/creationForms/steps/ScheduleStep.js#L66

En effet quand la date saisie en Début d’événement n'est pas valide (par exemple quand on veut modifier l'heure directement dans le champ input sans utiliser le timepicker), le JS plante et le formulaire disparait :

![image](https://user-images.githubusercontent.com/3025653/36080029-3f69a93e-0f8a-11e8-81ca-d5744e5f46af.png)

Il faudrait wrapper `this.state.startTime` dans un objet `moment` ou faire un check avant d'appeler la méthode `clone()`.

Pour reproduire : dans "Quand ?" sur https://agir.lafranceinsoumise.fr/evenements/creer/, rentrer une date de début d'événement invalide, le formulaire disparaît complètement.

**Comment by guilro** [comment]
Résolu, merci beaucoup du signalement !
