### ISSUE TITLE
Evénement mal localisé sur la carte après mise à jour de l'adresse

### ISSUE THREAD

**Issue by JeWaVe** [lafranceinsoumise/api-django#22]
Voir l'événément (passé) : https://agir.lafranceinsoumise.fr/evenements/c573dafe-3f60-4de2-84f1-54a42827ec8d/

Il a été créé à une adresse (le point bleu sur la carte), puis déplacé à une autre adresse (celle qui s'affiche en texte). 

Le point de la carte n'est pas mis à jour : 

![bug-ga-localisation-evenement](https://user-images.githubusercontent.com/11440561/48715047-5edf6580-ec14-11e8-8bc5-889ec5fc0f89.png)

**Comment by aktiur** [comment]
Complément d'information : 
- les coordonnées de l'événement n'étaient pas taggées (ni coordonnées manuelles, ni coordonnées automatiques)
- une nouvelle tentative de geocoding a replacé l'événement au bon endroit.

Pas d'idée pour le moment sur la façon dont l'événement s'est retrouvé dans cet état.
